Repository canonical/pgbouncer-operator, pull requests merged in 2025-04, with the labels that each got.

#523 Create SECURITY.md
  SECURITY.md
Labels: not bug or enhancement

#526 [MISC] Add noble base
  .github/workflows/ci.yaml
  charmcraft.yaml
  tests/integration/conftest.py
  tests/integration/relations/pgbouncer_provider/test_data_integrator.py
  tests/integration/relations/pgbouncer_provider/test_data_integrator_ha.py
  tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
  tests/integration/test_subordinates.py
  tests/integration/test_upgrade_data_integrator.py
Labels: enhancement, Libraries: Out of sync

#528 [MISC] Reenable cached build
  .github/workflows/ci.yaml
  tests/integration/test_upgrade.py
Labels: Libraries: Out of sync, not bug or enhancement

#531 [MISC] Fix renovate config
  .github/renovate.json5
Labels: Libraries: Out of sync, not bug or enhancement

#527 [DPE-6218] Static code analysis
  .github/workflows/tiobe_scan.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#532 [MISC] Update charm libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  pyproject.toml
  tests/integration/relations/test_backend_database.py
Labels: Libraries: Out of sync, not bug or enhancement

#343 [DPE-4683] socket config flag
  config.yaml
  src/config.py
  src/relations/pgbouncer_provider.py
  tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
  tests/integration/test_charm.py
  tests/integration/test_config.py
Labels: enhancement, Libraries: Out of sync

#536 [DPE-4683] Set read only host
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  src/relations/pgbouncer_provider.py
  tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Labels: bug, Libraries: Out of sync
